controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      publish_rate: 50

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    joints:
      - axis_joint_1
      - axis_joint_2
      - axis_joint_3
      - axis_joint_4
      - axis_joint_5
      - axis_joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 25.0
    action_monitor_rate: 10.0
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.02
      axis_joint_1:
        trajectory: 0.5
        goal: 0.1
      axis_joint_2:
        trajectory: 0.5
        goal: 0.1
      axis_joint_3:
        trajectory: 0.5
        goal: 0.1
      axis_joint_4:
        trajectory: 0.5
        goal: 0.1
      axis_joint_5:
        trajectory: 0.5
        goal: 0.1
      axis_joint_6:
        trajectory: 0.5
        goal: 0.1
    goal_tolerance:
      axis_joint_1: 0.05
      axis_joint_2: 0.05
      axis_joint_3: 0.05
      axis_joint_4: 0.05
      axis_joint_5: 0.05
      axis_joint_6: 0.05
    stopped_velocity_tolerance:
      axis_joint_1: 0.02
      axis_joint_2: 0.02
      axis_joint_3: 0.02
      axis_joint_4: 0.02
      axis_joint_5: 0.02
      axis_joint_6: 0.02