controller_manager: # collection of controllers
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:  # the name of the controller which can be find in xml file
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:  # the name of the second controller
      type: diff_drive_controller/DiffDriveController

joint_state_broadcaster:
  ros__parameters:
    joints:
      - front_left_wheel_joint
      - front_right_wheel_joint
      - rear_left_wheel_joint
      - rear_right_wheel_joint

diff_drive_controller:
  ros__parameters:  # parameters whcih can be find in yaml file
    left_wheel_names: ["front_left_wheel_joint", "rear_left_wheel_joint"]
    right_wheel_names: ["front_right_wheel_joint", "rear_right_wheel_joint"]

    wheel_separation: 0.36
    wheel_radius: 0.1

    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.0
        min_velocity: -1.0
        has_acceleration_limits: true
        max_acceleration: 0.8
        min_acceleration: -0.8

    angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.0
        min_velocity: -1.0
        has_acceleration_limits: true
        max_acceleration: 1.0
        min_acceleration: -1.0

    publish_rate: 50.0
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
    
    # Frames
    odom_frame_id: odom
    base_frame_id: base_link
    
    # Topics
    cmd_vel_timeout: 0.5
    
    # Enable odom tf
    enable_odom_tf: true
    
    # Velocity/position update
    use_stamped_vel: false
    
    # Additional parameters for better simulation
    velocity_rolling_window_size: 10
    linear.x.has_jerk_limits: false
    angular.z.has_jerk_limits: false